version: '3'
services:
  redis:
    image: "redis:4.0.6"
  expressjs-redis-example-app:    
    image: "expressjs-redis-example-app:latest"
    depends_on:
        - redis
  nginx-reverseproxy:
    image: "nginx-reverseproxy:latest"
    depends_on:
        - expressjs-redis-example-app
    ports:
     - "80:80"